site_name: People Depot Docs
repo_url: https://github.com/hackforla/peopledepot
repo_name: hackforla/peopledepot
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.expand
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    # - navigation.tabs.sticky
    - navigation.tracking
    - toc.integrate

plugins:
  - search
  - autolinks
  - awesome-pages
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - redoc-tag
  - render_swagger

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.details
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hackforla/peopledepot
    - icon: fontawesome/brands/slack
      link: https://hackforla.slack.com/archives/C02PTACSRJQ
    - icon: fontawesome/solid/paper-plane
      link: mailto:peopledepot@hackforla.org

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2020-2022, Civic Tech Structure

validation:
  absolute_links: relative_to_docs
  not_found: warn
  links:
    anchors: warn
    unrecognized_links: warn
  nav:
    omitted_files: warn

watch:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
