site_name: People Depot Docs
repo_url: https://github.com/hackforla/peopledepot
repo_name: hackforla/peopledepot
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking

plugins:
  - search
  - autolinks
  - awesome-pages

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.details
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: true

validation:
  absolute_links: relative_to_docs
  not_found: warn
  links:
    anchors: warn
    unrecognized_links: warn
  nav:
    omitted_files: warn

watch:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
